/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f0f1f1",
        "on-primary": "#fbfb00",
        "on-background": "#1e1e1e",
        "outline": "#767777",
        "on-primary-container": "#5a5a00",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#f3f300",
        "tertiary-fixed": "#3fff8b",
        "primary": "#5f5f00",
        "on-secondary-fixed-variant": "#0042c9",
        "secondary-fixed": "#c5d0ff",
        "inverse-primary": "#ffff00",
        "tertiary": "#006a33",
        "on-tertiary-fixed": "#004820",
        "on-error-container": "#520c00",
        "tertiary-container": "#3fff8b",
        "primary-dim": "#525200",
        "error": "#b02500",
        "surface-container-high": "#e1e3e3",
        "secondary-container": "#c5d0ff",
        "on-tertiary": "#cdffd3",
        "secondary": "#004be2",
        "primary-fixed": "#f3f300",
        "on-surface": "#1e1e1e",
        "surface-bright": "#fbfbfa",
        "primary-fixed-dim": "#e4e400",
        "surface-variant": "#dbdddd",
        "on-primary-fixed": "#474700",
        "surface-dim": "#d3d5d5",
        "error-dim": "#b92902",
        "inverse-on-surface": "#9c9d9d",
        "background": "#fbfbfa",
        "secondary-dim": "#0041c7",
        "on-secondary": "#f2f1ff",
        "tertiary-dim": "#005c2b",
        "secondary-fixed-dim": "#b3c1ff",
        "surface": "#fbfbfa",
        "on-tertiary-container": "#005d2c",
        "on-error": "#ffefec",
        "on-surface-variant": "#5a5c5c",
        "on-secondary-fixed": "#002a88",
        "surface-tint": "#5f5f00",
        "outline-variant": "#acadad",
        "on-tertiary-fixed-variant": "#006832",
        "on-primary-fixed-variant": "#646400",
        "surface-container-highest": "#dbdddd",
        "error-container": "#f95630",
        "tertiary-fixed-dim": "#24f07e",
        "surface-container": "#e7e8e8",
        "inverse-surface": "#0c0f0f",
        "on-secondary-container": "#003ab4",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
